name: konquer
channels:
  - conda-forge
dependencies:
  - cartopy
  - cdsapi
  - geopandas
  - hvplot
  - regionmask
  - pandas
  - numpy
  - xarray
  - matplotlib
  - cartopy
  - tqdm
  - netcdf4
  - bottleneck
  - bokeh<2
  - geoviews
  - ipywidgets